/**
 * Delter Airlines
 * Documentation for delter airlines
 *
 * OpenAPI spec version: 1.1.1
 * Contact: pdb145@msstate.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Path {
    ticketID?: number;
    username?: string;
    name?: string;
}
