/**
 * Hurts Car API
 * Hurts Car Rental API
 *
 * OpenAPI spec version: 1.1.1b
 * Contact: support@softwarebois.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PurchasedVehicle } from './purchasedVehicle';
import { Vehicle } from './vehicle';


export interface Reservation {
    reservationInfo: PurchasedVehicle;
    vehicleInfo: Vehicle;
}
