/**
 * AirDND API
 * AirDND's API
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';

import { Listing } from '../model/listing';
import { LocationListings } from '../model/locationListings';
import { Pricing } from '../model/pricing';
import { Reservation } from '../model/reservation';
import { Reservations } from '../model/reservations';
import { Review } from '../model/review';
import { Reviews } from '../model/reviews';
import { User } from '../model/user';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AdminsService {

    protected basePath = 'https://0.0.0.0:80/AirDND/AirDND/1.0.5';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * adds a listing
     * Adds a listing in the system
     * @param listing Listing to add
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerAddListing(listing: Listing, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerAddListing(listing: Listing, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerAddListing(listing: Listing, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerAddListing(listing: Listing, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listing === null || listing === undefined) {
            throw new Error('Required parameter listing was null or undefined when calling controllersAdminsControllerAddListing.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/listings`,
            listing,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * add a reservation
     * Adds a reservation in the system
     * @param listingId Listing Id
     * @param reservation reservation to add
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerAddReservation(listingId: string, reservation: Reservation, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerAddReservation(listingId: string, reservation: Reservation, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerAddReservation(listingId: string, reservation: Reservation, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerAddReservation(listingId: string, reservation: Reservation, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listingId === null || listingId === undefined) {
            throw new Error('Required parameter listingId was null or undefined when calling controllersAdminsControllerAddReservation.');
        }
        if (reservation === null || reservation === undefined) {
            throw new Error('Required parameter reservation was null or undefined when calling controllersAdminsControllerAddReservation.');
        }

        let headers = this.defaultHeaders;
        if (listingId !== undefined && listingId !== null) {
            headers = headers.set('listingId', String(listingId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/reservations`,
            reservation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * adds a review
     * Adds a review of a listing
     * @param review Review to add
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerAddReview(review: Review, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerAddReview(review: Review, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerAddReview(review: Review, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerAddReview(review: Review, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (review === null || review === undefined) {
            throw new Error('Required parameter review was null or undefined when calling controllersAdminsControllerAddReview.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/reviews`,
            review,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * adds a user
     * Adds a user in the system
     * @param user User to add
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerAddUser(user: User, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerAddUser(user: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerAddUser(user: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerAddUser(user: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (user === null || user === undefined) {
            throw new Error('Required parameter user was null or undefined when calling controllersAdminsControllerAddUser.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/users`,
            user,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get a listing
     * get a listing in the system
     * @param listingId Listing Id to update
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerGetListing(listingId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerGetListing(listingId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerGetListing(listingId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerGetListing(listingId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listingId === null || listingId === undefined) {
            throw new Error('Required parameter listingId was null or undefined when calling controllersAdminsControllerGetListing.');
        }

        let headers = this.defaultHeaders;
        if (listingId !== undefined && listingId !== null) {
            headers = headers.set('listingId', String(listingId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<any>(`${this.basePath}/listings`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get a reservation
     * get a reservation in the system
     * @param reservationId Reservation Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerGetReservation(reservationId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerGetReservation(reservationId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerGetReservation(reservationId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerGetReservation(reservationId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (reservationId === null || reservationId === undefined) {
            throw new Error('Required parameter reservationId was null or undefined when calling controllersAdminsControllerGetReservation.');
        }

        let headers = this.defaultHeaders;
        if (reservationId !== undefined && reservationId !== null) {
            headers = headers.set('reservationId', String(reservationId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<any>(`${this.basePath}/reservations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all reservations
     * reservations from AirDND listings
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerGetReservations(observe?: 'body', reportProgress?: boolean): Observable<Reservations>;
    public controllersAdminsControllerGetReservations(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Reservations>>;
    public controllersAdminsControllerGetReservations(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Reservations>>;
    public controllersAdminsControllerGetReservations(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Reservations>(`${this.basePath}/history`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get accumulated revenue
     * Revenue from AirDND listings
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerGetRevenue(observe?: 'body', reportProgress?: boolean): Observable<Pricing>;
    public controllersAdminsControllerGetRevenue(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Pricing>>;
    public controllersAdminsControllerGetRevenue(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Pricing>>;
    public controllersAdminsControllerGetRevenue(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Pricing>(`${this.basePath}/revenue`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get a review
     * get a review of a listing
     * @param reviewId Review Id to get
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerGetReview(reviewId: string, observe?: 'body', reportProgress?: boolean): Observable<Review>;
    public controllersAdminsControllerGetReview(reviewId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Review>>;
    public controllersAdminsControllerGetReview(reviewId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Review>>;
    public controllersAdminsControllerGetReview(reviewId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (reviewId === null || reviewId === undefined) {
            throw new Error('Required parameter reviewId was null or undefined when calling controllersAdminsControllerGetReview.');
        }

        let headers = this.defaultHeaders;
        if (reviewId !== undefined && reviewId !== null) {
            headers = headers.set('reviewId', String(reviewId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Review>(`${this.basePath}/reviews`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get a review
     * get a reviews for a listing
     * @param listingId listing Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerGetReviews(listingId: string, observe?: 'body', reportProgress?: boolean): Observable<Reviews>;
    public controllersAdminsControllerGetReviews(listingId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Reviews>>;
    public controllersAdminsControllerGetReviews(listingId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Reviews>>;
    public controllersAdminsControllerGetReviews(listingId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listingId === null || listingId === undefined) {
            throw new Error('Required parameter listingId was null or undefined when calling controllersAdminsControllerGetReviews.');
        }

        let headers = this.defaultHeaders;
        if (listingId !== undefined && listingId !== null) {
            headers = headers.set('listingId', String(listingId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Reviews>(`${this.basePath}/listings/reviews`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get a user
     * get a user from the system
     * @param userId User ID to update
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerGetUser(userId: string, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public controllersAdminsControllerGetUser(userId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public controllersAdminsControllerGetUser(userId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public controllersAdminsControllerGetUser(userId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling controllersAdminsControllerGetUser.');
        }

        let headers = this.defaultHeaders;
        if (userId !== undefined && userId !== null) {
            headers = headers.set('userId', String(userId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<User>(`${this.basePath}/users`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * remove a listing
     * remove a listing in the system
     * @param listingId Listing Id to remove
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerRemoveListing(listingId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerRemoveListing(listingId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerRemoveListing(listingId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerRemoveListing(listingId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listingId === null || listingId === undefined) {
            throw new Error('Required parameter listingId was null or undefined when calling controllersAdminsControllerRemoveListing.');
        }

        let headers = this.defaultHeaders;
        if (listingId !== undefined && listingId !== null) {
            headers = headers.set('listingId', String(listingId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/listings`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * remove a reservation
     * remove a reservation in the system
     * @param reservationId reservation Id to remove
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerRemoveReservation(reservationId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerRemoveReservation(reservationId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerRemoveReservation(reservationId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerRemoveReservation(reservationId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (reservationId === null || reservationId === undefined) {
            throw new Error('Required parameter reservationId was null or undefined when calling controllersAdminsControllerRemoveReservation.');
        }

        let headers = this.defaultHeaders;
        if (reservationId !== undefined && reservationId !== null) {
            headers = headers.set('reservationId', String(reservationId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/reservations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * remove a review
     * remove a review of a listing
     * @param reviewId Review Id to remove
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerRemoveReview(reviewId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerRemoveReview(reviewId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerRemoveReview(reviewId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerRemoveReview(reviewId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (reviewId === null || reviewId === undefined) {
            throw new Error('Required parameter reviewId was null or undefined when calling controllersAdminsControllerRemoveReview.');
        }

        let headers = this.defaultHeaders;
        if (reviewId !== undefined && reviewId !== null) {
            headers = headers.set('reviewId', String(reviewId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/reviews`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * remove a user
     * remove a user in the system
     * @param userId User Id to remove
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerRemoveUser(userId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerRemoveUser(userId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerRemoveUser(userId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerRemoveUser(userId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling controllersAdminsControllerRemoveUser.');
        }

        let headers = this.defaultHeaders;
        if (userId !== undefined && userId !== null) {
            headers = headers.set('userId', String(userId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/users`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * reset data to default
     * Resets AirDND db to start state
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerReset(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerReset(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerReset(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerReset(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/reset`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * searches listings
     * By passing in the appropriate options, you can search for available listings in the system 
     * @param location pass a location
     * @param startDate has times available after
     * @param endDate has times available before
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerSearchListing(location: string, startDate?: string, endDate?: string, observe?: 'body', reportProgress?: boolean): Observable<LocationListings>;
    public controllersAdminsControllerSearchListing(location: string, startDate?: string, endDate?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LocationListings>>;
    public controllersAdminsControllerSearchListing(location: string, startDate?: string, endDate?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LocationListings>>;
    public controllersAdminsControllerSearchListing(location: string, startDate?: string, endDate?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (location === null || location === undefined) {
            throw new Error('Required parameter location was null or undefined when calling controllersAdminsControllerSearchListing.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (location !== undefined) {
            queryParameters = queryParameters.set('location', <any>location);
        }
        if (startDate !== undefined) {
            queryParameters = queryParameters.set('startDate', <any>startDate);
        }
        if (endDate !== undefined) {
            queryParameters = queryParameters.set('endDate', <any>endDate);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<LocationListings>(`${this.basePath}/listings/locations`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update a listing
     * Updates a listing in the system
     * @param listingId Listing Id to update
     * @param listing New listing information
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerUpdateListing(listingId: string, listing: Listing, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerUpdateListing(listingId: string, listing: Listing, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerUpdateListing(listingId: string, listing: Listing, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerUpdateListing(listingId: string, listing: Listing, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listingId === null || listingId === undefined) {
            throw new Error('Required parameter listingId was null or undefined when calling controllersAdminsControllerUpdateListing.');
        }
        if (listing === null || listing === undefined) {
            throw new Error('Required parameter listing was null or undefined when calling controllersAdminsControllerUpdateListing.');
        }

        let headers = this.defaultHeaders;
        if (listingId !== undefined && listingId !== null) {
            headers = headers.set('listingId', String(listingId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/listings`,
            listing,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update a reservation
     * Updates a reservation in the system
     * @param reservationId Reservation Id to update
     * @param reservation New reservation information
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerUpdateReservation(reservationId: string, reservation: Reservation, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerUpdateReservation(reservationId: string, reservation: Reservation, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerUpdateReservation(reservationId: string, reservation: Reservation, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerUpdateReservation(reservationId: string, reservation: Reservation, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (reservationId === null || reservationId === undefined) {
            throw new Error('Required parameter reservationId was null or undefined when calling controllersAdminsControllerUpdateReservation.');
        }
        if (reservation === null || reservation === undefined) {
            throw new Error('Required parameter reservation was null or undefined when calling controllersAdminsControllerUpdateReservation.');
        }

        let headers = this.defaultHeaders;
        if (reservationId !== undefined && reservationId !== null) {
            headers = headers.set('reservationId', String(reservationId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/reservations`,
            reservation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update a review
     * Updates a review of a listing
     * @param review New review information
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerUpdateReview(review: Review, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerUpdateReview(review: Review, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerUpdateReview(review: Review, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerUpdateReview(review: Review, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (review === null || review === undefined) {
            throw new Error('Required parameter review was null or undefined when calling controllersAdminsControllerUpdateReview.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/reviews`,
            review,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update a user
     * Updates a user in the system
     * @param userId User Id to update
     * @param user New user information
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public controllersAdminsControllerUpdateUser(userId: string, user: User, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public controllersAdminsControllerUpdateUser(userId: string, user: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public controllersAdminsControllerUpdateUser(userId: string, user: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public controllersAdminsControllerUpdateUser(userId: string, user: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling controllersAdminsControllerUpdateUser.');
        }
        if (user === null || user === undefined) {
            throw new Error('Required parameter user was null or undefined when calling controllersAdminsControllerUpdateUser.');
        }

        let headers = this.defaultHeaders;
        if (userId !== undefined && userId !== null) {
            headers = headers.set('userId', String(userId));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/users`,
            user,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
