apiVersion: v1
kind: Pod
metadata:
  name: user-saves
  labels:
    name: user-saves
spec:
  containers:
    - image: launcher.gcr.io/google/mongodb3
      name: mongo
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: data
          mountPath: /data/db
          subPath: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
