/**
 * Hilbun Hotels
 * RESTful API for a fictitious hotel chain. Created for a MSU Software Architecture course.
 *
 * OpenAPI spec version: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Room {
    roomId?: number;
    roomNumber?: number;
    roomType?: string;
    roomCost?: number;
    location?: Room.LocationEnum;
    /**
     * room status in the location
     */
    status?: Room.StatusEnum;
}
export namespace Room {
    export type LocationEnum = 'Starkville, MS' | 'Atlanta, GA';
    export const LocationEnum = {
        StarkvilleMS: 'Starkville, MS' as LocationEnum,
        AtlantaGA: 'Atlanta, GA' as LocationEnum
    }
    export type StatusEnum = 'available' | 'unavilable';
    export const StatusEnum = {
        Available: 'available' as StatusEnum,
        Unavilable: 'unavilable' as StatusEnum
    }
}
