/**
 * AirDND API
 * AirDND's API
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Review } from './review';


export interface Reviews extends Array<Review> {
}
