/**
 * AirDND API
 * AirDND's API
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User {
    acceptanceRate: string;
    friendsCount: number;
    hardSuspended: boolean;
    id: number;
    listingsCount: number;
    publiclyVisibleWishlistsCount: number;
    recommendationCount: number;
    responseRate: string;
    responseTime: string;
    revieweeCount: number;
    softSuspended: boolean;
    suspended: boolean;
    totalListingsCount: number;
    wishlistsCount: number;
}
