/**
 * Carnivore Cruise Lines API
 * This is an API to access the information on Carnivore Cruise Lines
 *
 * OpenAPI spec version: 1.3.0
 * Contact: jcw931@msstate.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';

import { CruiseItem } from '../model/cruiseItem';
import { HistoryItem } from '../model/historyItem';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DevelopersService {

    protected basePath = 'https://virtserver.swaggerhub.com/Carnivore-Cruises/Carnivore_Cruise_Lines/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Gets accumulated total for all items purchased
     * adds the amounts for items purchased to get accumulated total
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTotal(observe?: 'body', reportProgress?: boolean): Observable<Array<HistoryItem>>;
    public getTotal(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<HistoryItem>>>;
    public getTotal(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<HistoryItem>>>;
    public getTotal(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<HistoryItem>>(`${this.basePath}/system/history`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update inventory availability
     * update quantity of inventory based on previous purchases. The quantity is either 1 or 0 only
     * @param itemID 
     * @param availability 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inventoryItemIDAvailabilityPut(itemID: string, availability: boolean, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public inventoryItemIDAvailabilityPut(itemID: string, availability: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public inventoryItemIDAvailabilityPut(itemID: string, availability: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public inventoryItemIDAvailabilityPut(itemID: string, availability: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemID === null || itemID === undefined) {
            throw new Error('Required parameter itemID was null or undefined when calling inventoryItemIDAvailabilityPut.');
        }
        if (availability === null || availability === undefined) {
            throw new Error('Required parameter availability was null or undefined when calling inventoryItemIDAvailabilityPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.put<any>(`${this.basePath}/inventory/${encodeURIComponent(String(itemID))}/${encodeURIComponent(String(availability))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * searches inventory of avaible cruises
     * By passing in the appropriate options, you can search for available inventory in the system 
     * @param limit maximum number of records to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchCruises(limit?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CruiseItem>>;
    public searchCruises(limit?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CruiseItem>>>;
    public searchCruises(limit?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CruiseItem>>>;
    public searchCruises(limit?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<CruiseItem>>(`${this.basePath}/inventory`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * searches inventory of avaible cruises in location
     * By passing in the appropriate options, you can search for available inventory in the system 
     * @param cityState 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchForLocation(cityState: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CruiseItem>>;
    public searchForLocation(cityState: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CruiseItem>>>;
    public searchForLocation(cityState: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CruiseItem>>>;
    public searchForLocation(cityState: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (cityState === null || cityState === undefined) {
            throw new Error('Required parameter cityState was null or undefined when calling searchForLocation.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<CruiseItem>>(`${this.basePath}/inventory/location/${encodeURIComponent(String(cityState))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * User selects item for purchase
     * User can select an item in the inventory for purchase. Used for adding up the accumulated total
     * @param itemID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public selectItem(itemID: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CruiseItem>>;
    public selectItem(itemID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CruiseItem>>>;
    public selectItem(itemID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CruiseItem>>>;
    public selectItem(itemID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemID === null || itemID === undefined) {
            throw new Error('Required parameter itemID was null or undefined when calling selectItem.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.put<Array<CruiseItem>>(`${this.basePath}/system/purchase/${encodeURIComponent(String(itemID))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
