# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, userdata: str=None):  # noqa: E501
        """User - a model defined in Swagger

        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param userdata: The userdata of this User.  # noqa: E501
        :type userdata: str
        """
        self.swagger_types = {
            'username': str,
            'userdata': str
        }

        self.attribute_map = {
            'username': 'username',
            'userdata': 'userdata'
        }

        self._username = username
        self._userdata = userdata

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this User.


        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this User.


        :param username: The username of this User.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def userdata(self) -> str:
        """Gets the userdata of this User.


        :return: The userdata of this User.
        :rtype: str
        """
        return self._userdata

    @userdata.setter
    def userdata(self, userdata: str):
        """Sets the userdata of this User.


        :param userdata: The userdata of this User.
        :type userdata: str
        """
        if userdata is None:
            raise ValueError("Invalid value for `userdata`, must not be `None`")  # noqa: E501

        self._userdata = userdata
