# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, orders: List[str]=None):  # noqa: E501
        """User - a model defined in Swagger

        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param orders: The orders of this User.  # noqa: E501
        :type orders: List[str]
        """
        self.swagger_types = {
            'username': str,
            'orders': List[str]
        }

        self.attribute_map = {
            'username': 'username',
            'orders': 'orders'
        }

        self._username = username
        self._orders = orders

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this User.


        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this User.


        :param username: The username of this User.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def orders(self) -> List[str]:
        """Gets the orders of this User.


        :return: The orders of this User.
        :rtype: List[str]
        """
        return self._orders

    @orders.setter
    def orders(self, orders: List[str]):
        """Sets the orders of this User.


        :param orders: The orders of this User.
        :type orders: List[str]
        """
        if orders is None:
            raise ValueError("Invalid value for `orders`, must not be `None`")  # noqa: E501

        self._orders = orders
