/**
 * Carnivore Cruise Lines API
 * This is an API to access the information on Carnivore Cruise Lines
 *
 * OpenAPI spec version: 1.3.2
 * Contact: jcw931@msstate.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CruiseItem {
    itemID: string;
    cruiseLinerID: string;
    roomID: number;
    available: boolean;
    cost: number;
    name: string;
    description: string;
    roomCapacity: number;
    fromLocation: string;
    departureDate: string;
    returnDate: string;
    duration: number;
}
