/**
 * Carnivore Cruise Lines API
 * This is an API to access the information on Carnivore Cruise Lines
 *
 * OpenAPI spec version: 1.3.3
 * Contact: jcw931@msstate.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface HistoryItem {
    itemID: string;
    numberSold: number;
}
